"""empty message

Revision ID: 36b65a5d3f51
Revises: 922abe05ca4c
Create Date: 2022-12-09 09:26:37.030419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b65a5d3f51'
down_revision = '922abe05ca4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('planet_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rotation_period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_date',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('update_date',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.create_unique_constraint(None, ['update_date'])
        batch_op.create_unique_constraint(None, ['created_date'])
        batch_op.create_unique_constraint(None, ['diameter'])
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_unique_constraint(None, ['rotation_period'])
        batch_op.create_unique_constraint(None, ['orbital_period'])
        batch_op.create_unique_constraint(None, ['climate'])
        batch_op.create_unique_constraint(None, ['population'])
        batch_op.create_unique_constraint(None, ['description'])
        batch_op.create_unique_constraint(None, ['url'])
        batch_op.create_unique_constraint(None, ['planet_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('update_date',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('created_date',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('diameter',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rotation_period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('planet_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
